base:
  config:
    tidb:
      hostname: leg.liudongyang.top
      port: 6603
    nacos:
      hostname: leg.liudongyang.top
      port: 8848

spring:
  application:
    name: provider-admin-login-log-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/mplus_ums_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: class1013leg
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.leg.blog.plus.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.leg.blog.plus.provider.domain
  mapper-locations: classpath:mapper/*.xml