version: "3.5"
services:
  admin-ums:
    image: admin-ums
    container_name: admin-ums
    restart: always
    build:
      context: admin/provider-admin-ums-service
      dockerfile: Dockerfile
    networks:
      - oauth

  admin-login:
    image: admin-login
    container_name: admin-login
    restart: always
    build:
      context: admin/provider-admin-login-log-service
      dockerfile: Dockerfile
    networks:
      - oauth

  business-reg:
    image: business-reg
    container_name: business-reg
    restart: always
    build:
      context: admin/business-reg-service
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - admin-ums
      - admin-login
    networks:
      - oauth

  business-profile:
    image: business-profile
    container_name: business-profile
    restart: always
    build:
      context: admin/business-profile-service
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    depends_on:
      - business-reg
    networks:
      - oauth

#  message-admin-login:
#    image: message-admin-login
#    container_name: message-admin-login
#    restart: always
#    build:
#      context: admin/message-admin-login-log
#      dockerfile: Dockerfile
#    depends_on:
#      - admin-login
#      - admin-ums

#  cloud-message:
#    image: cloud-message
#    container_name: cloud-message
#    restart: always
#    build:
#      context: admin/cloud-message-service
#      dockerfile: Dockerfile
#    depends_on:
#      - admin-login
#      - admin-ums

  cloud-upload:
    image: cloud-upload
    container_name: cloud-upload
    restart: always
    build:
      context: admin/cloud-upload-service
      dockerfile: Dockerfile
    ports:
      - 10001:10001
    depends_on:
      - business-profile
    networks:
      - oauth

  business-oauth2:
    image: business-oauth2
    container_name: business-oauth2
    restart: always
    build:
      context: admin/business-oauth2-service
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - business-profile
    networks:
      - oauth

  gateway:
    image: gateway
    container_name: gateway
    restart: always
    build:
      context: admin/gateway
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - business-oauth2
    networks:
      - oauth

networks:
  oauth:
