cp provider/provider-admin-login-log-service/target/provider-admin-login-log-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/provider-admin-login-log-service/provider-admin-login-log-service.jar
cp provider/provider-admin-ums-service/target/provider-admin-ums-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/provider-admin-ums-service/provider-admin-ums-service.jar
cp business/business-reg-service/target/business-reg-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/business-reg-service/business-reg-service.jar
cp business/business-profile-service/target/business-profile-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/business-profile-service/business-profile-service.jar
cp cloud/cloud-message-service/target/cloud-message-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/cloud-message-service/cloud-message-service.jar
cp cloud/cloud-upload-service/target/cloud-upload-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/cloud-upload-service/cloud-upload-service.jar
cp business/business-oauth2-service/target/business-oauth2-service-0.0.1-SNAPSHOT.jar simple-deploy/admin/business-oauth2-service/business-oauth2-service.jar
cp gateway/target/gateway-0.0.1-SNAPSHOT.jar simple-deploy/admin/gateway/gateway.jar
cp message/message-admin-login-log/target/message-admin-login-log-0.0.1-SNAPSHOT.jar simple-deploy/admin/message-admin-login-log/message-admin-login-log.jar
