base:
  config:
    oauth:
      hostname: oauth.liudongyang.top
      port: 9001
    nacos:
      hostname: leg.liudongyang.top
      port: 8848
    sentile:
      hostname: leg.liudongyang.top
      port: 8080
    redis:
      hostname: leg.liudongyang.top
      port: 6379

spring:
  application:
    name: business-profile
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    sentinel:
      transport:
        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}
  redis:
    # 你 Redis 主机地址
    host: ${base.config.redis.hostname}
    # 你 Redis 主机端口
    port: ${base.config.redis.port}
    # 集群配置，上生产后使用
    #   cluster:
    #     nodes: ${base.config.redis.hostname}:${base.config.redis.port}
    # 我们使用 Lettuce 客户端，比 Jedis 更高效
    lettuce:
      # 连接池配置
      pool:
        # 连接池中的最小空闲连接，默认 0
        min-idle: 0
        # 连接池中的最大空闲连接，默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1ms
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-active: 8
      # Redis 高可用集群，由于 K8S 帮我们实现了高可用，这个可以忽略了
    sentinel:
      master: mymaster
      nodes: ${base.config.redis.hostname}:26379

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

dubbo:
  scan:
    base-packages: com.leg.blog.plus.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

server:
  port: 9002

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"